-- Script DDL para la creacion de las tablas de la base de datos.
CREATE TABLE IF NOT EXISTS tb_master_control (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_sistema timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tamanio_terreno integer NOT NULL CHECK (tamanio_terreno >= 1),
    despegue_x integer NOT NULL CHECK (despegue_x >= 0),
    despegue_y integer NOT NULL CHECK (despegue_y >= 0)
);

CREATE TABLE IF NOT EXISTS tb_det_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_master_control integer NOT NULL,
    paso_actual integer NOT NULL,
    posicion_x integer NOT NULL,
    posicion_y integer NOT NULL,
    CONSTRAINT fk_tb_det_log_master_control
        FOREIGN KEY (id_master_control)
        REFERENCES tb_master_control (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_tb_det_log_id_master_control
    ON tb_det_log (id_master_control);
